<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php
$cart = $this->getCommonVar('cart');?>

<div class="row">
    <div class="small-12 columns">
        <h1><?php echo $variables['@header'];?></h1>
    </div>
</div>
<section class="basket">
<?php if(is_array($cart) && isset($cart['items']) && count($cart['items']['nodes:item'])):?>
    <form action="/emarket/checkout/" method="POST">
        <?php echo $this->render(array(
            'cart' => $cart
        ), 'modules/emarket/cart/items');?>

        <?php echo $this->render(null, 'modules/emarket/cart/checkout');?>
    </form>
<?php else:?>
    <div class="row">
        <div class="small-12 columns">
            <p>В вашей корзине нет товаров</p>
        </div>
    </div>
<?php endif;?>
</section>