<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<div class="row">
    <div class="small-12 columns">
        <h1>Вы успешно зарегистрировались</h1>
    </div>
</div>
<section>
    <div class="row">
        <div class="small-9 columns">
            <p>Благодарим вас за регистрацию!</p>
            <a class="button radius" href="/">Посмотреть каталог букетов</a>
        </div>

        <div class="small-3 columns">
            <?php echo $this->render(null, 'blocks/benefits');?>
        </div>
    </div>
</section>