<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<div data-alert class="alert-box cart-added" id="cart_added" style="display: none;">
    <div class="row">
        <div class="medium-12 columns">
            <span class="h3">Товар добавлен в корзину</span>
            <div data-cart="popup-order"></div>
        </div>
        <div class="medium-6 columns">
            <a class="button radius secondary expand close" href="#">Продолжить покупки</a>
        </div>
        <div class="medium-6 columns">
            <a class="button radius info expand" href="/emarket/cart/">Оформить заказ</a>
        </div>
    </div>
</div>