<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php $page = $variables['full:page'];
/* @var umiHierarchyElement $page*/?>
<div class="row">
    <div class="small-12 columns">
        <h1 umi:element-id="<?php echo $page->getId();?>" umi:field-name="h1"><?php echo $page->getValue('h1');?></h1>
    </div>
</div>
<section>
    <div class="row">
        <div class="large-9 columns" umi:element-id="<?php echo $page->getId();?>" umi:field-name="content">
            <?php echo $page->getValue('content');?>
        </div>
        <div class="large-3 columns">
            <?php echo $this->render(null, 'blocks/benefits');?>
        </div>
    </div>
</section>
