<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php $message = $this->macros('webforms', 'posted');?>
<div class="row">
    <div class="small-12 columns">
        <h1><?php echo getArrayKey($variables, '@header');?></h1>
    </div>
</div>
<section>
    <div class="row">
        <div class="small-9 columns">
            <p><?php echo $message;?></p>
        </div>
        <div class="small-3 columns">
            <?php echo $this->render(null, 'blocks/benefits');?>
        </div>
    </div>
</section>
