<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<footer>
    <div class="row">
        <div class="medium-9 columns">
            <?php echo $this->render(null, 'blocks/footer/top_menu');?>
        </div>
        <div class="medium-3 columns">
            <form method="GET" action="/search/search_do/">
                <input class="radius" type="search" name="search_string" placeholder="Искать" />
            </form>
        </div>
        <div class="small-12 columns">
            <hr />
        </div>
        <div class="medium-9 columns">
            <?php echo $this->render(null, 'blocks/footer/bottom_menu');?>
        </div>
        <div class="medium-3 columns text-right small-only-text-center">
            <?php echo $this->render(null, 'blocks/footer/contacts');?>
        </div>
    </div>
    <div class="copy">
        <div class="row">
            <div class="medium-9 columns small-only-text-center" umi:object-id="<?php echo SITE_CONFIG_ID;?>" umi:field-name="footer_copyright">
                <?php echo $this->getConfigValue('footer_copyright');?>
            </div>
            <div class="medium-3 columns text-right small-only-text-center">
                <a href="http://uniteddesign.ru/" target="_blank">Сделано в UD</a>
            </div>
        </div>
    </div>
</footer>