<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php
$phone = $this->getConfigValue('footer_phone');
?>
<div class="info">
    <?php if($phone):?>
        <a class="phone" href="tel:<?php echo $this->preparePhoneLink($phone);?>" umi:object-id="<?php echo SITE_CONFIG_ID;?>" umi:field-name="header_phone"><?php echo $phone;?></a>
    <?php endif;?>
    <small><a class="callback modal" href="#callback">Заказать звонок</a></small>
</div>