<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php
$cart = getArrayKey($variables, 'cart');
if(!$cart) {
    $cart = $this->getCommonVar('cart');
}
if(is_array($cart) && isset($cart['items']) && count($cart['items']['nodes:item'])):?>
    <div class="checkout right full" data-cart="header">
        <a class="checkout-button" href="/emarket/cart/">
            <i class="material-icons">local_grocery_store</i><span class="text"> Корзина </span><span class="label info round" data-cart="amount"><?php echo $cart['summary']['amount'];?></span>
        </a>
        <div class="checkout-order">
            <div class="checkout-order-inner" data-cart="header-order">
                <?php echo $this->render($cart, 'blocks/header/blocks/cart/order');?>
            </div>
        </div>
    </div>
<?php else:?>
    <div class="checkout right" data-cart="header">
        <a class="checkout-button" href="/emarket/cart/">
            <i class="material-icons">local_grocery_store</i> Корзина <span class="label info round" data-cart="amount">0</span>
        </a>
        <div class="checkout-order">
            <div class="checkout-order-inner" data-cart="header-order"></div>
        </div>
    </div>
<?php endif;?>