<?php /** @var umiTemplaterPHP $this */ ?>
<?php /** @var array $variables */ ?>
<?php
try {
    $menu = $this->macros('menu', 'draw', array('top'));
} catch(Exception $e) {
    $menu = array();
}
if(is_array($menu) && isset($menu['nodes:item'])):?>
<section class="top-menu">
    <div class="row">
        <div class="small-12 columns">
            <ul class="inline-list">
                <?php foreach($menu['nodes:item'] as $item):
                    if(!$this->isMenuItemActive($item)) {
                        continue;
                    }
                    $isSelected = $this->isMenuItemSelected($item);
                    $itemId = getArrayKey($item, 'attribute:rel') == 'page' ? getArrayKey($item, 'attribute:id') : false;
                    ?>
                    <li<?php if($isSelected):?> class="active"<?php endif;?>><a href="<?php echo $item['attribute:link'];?>"<?php if($itemId):?> umi:element-id="<?php echo $itemId;?>" umi:field-name="name"<?php endif;?>><?php echo $item['attribute:name'];?></a></li>
                <?php endforeach;?>
            </ul>
        </div>
    </div>
</section>
<?php endif;?>